import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
async function sha512(value:string){const hash=await crypto.subtle.digest("SHA-512",new TextEncoder().encode(value));return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("")}
function buildRedirect(req:Request,path:string){const u=new URL(req.url);const explicit=u.searchParams.get("redirect");if(explicit)return explicit;const base=Deno.env.get("APP_BASE_URL")??"";const appt=u.searchParams.get("appointment");const suffix=appt?`${path}?appointment=${encodeURIComponent(appt)}`:path;return base?`${base}${suffix}`:suffix}
function textResponse(body:string,status=200){return new Response(body,{status,headers:corsHeaders})}
async function awardBundleCredits(admin:ReturnType<typeof createClient>,txnid:string){const {data:a}=await admin.from("appointments").select("id,customer_id,specialist_id,tier_id,bundle_credits_awarded_at").eq("payu_txn_id",txnid).maybeSingle();if(!a||a.bundle_credits_awarded_at)return;const {data:t}=await admin.from("specialist_tiers").select("session_count,credit_points,tier_type").eq("id",a.tier_id).maybeSingle();if(t?.tier_type!=="bundle")return;const points=Math.max(Number(t?.credit_points??0),Number(t?.session_count??1)*2);const remaining=Math.max(0,points-2);if(remaining>0){const {data:existing}=await admin.from("customer_specialist_credits").select("id,credit_points").eq("customer_id",a.customer_id).eq("specialist_id",a.specialist_id).maybeSingle();if(existing)await admin.from("customer_specialist_credits").update({credit_points:existing.credit_points+remaining,updated_at:new Date().toISOString()}).eq("id",existing.id);else await admin.from("customer_specialist_credits").insert({customer_id:a.customer_id,specialist_id:a.specialist_id,credit_points:remaining})}await admin.from("appointments").update({bundle_credits_awarded_at:new Date().toISOString()}).eq("id",a.id).is("bundle_credits_awarded_at",null)}
async function notifyBooking(appointmentId:string){const url=Deno.env.get("SUPABASE_URL");const key=Deno.env.get("SUPABASE_ANON_KEY");if(!url||!key)return;try{await fetch(`${url}/functions/v1/appointment-notifications`,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${key}`},body:JSON.stringify({action:"booking",appointment_id:appointmentId})})}catch(error){console.error("booking notification failed",error)}}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{headers:corsHeaders});try{const form=await req.formData();const get=(k:string)=>String(form.get(k)??"");const status=get("status"),key=get("key"),txnid=get("txnid"),amount=get("amount"),productinfo=get("productinfo"),firstname=get("firstname"),email=get("email"),postedHash=get("hash").toLowerCase(),mihpayid=get("mihpayid"),salt=Deno.env.get("PAYU_MERCHANT_SALT"),merchantKey=Deno.env.get("PAYU_MERCHANT_KEY");if(!salt||!merchantKey)return textResponse("PayU webhook is not configured",500);if(!postedHash||!txnid||!status)return textResponse("missing PayU fields",400);if(key&&key!==merchantKey)return textResponse("invalid merchant key",400);const calculatedHash=await sha512(`${salt}|${status}|||||||||||${email}|${firstname}|${productinfo}|${amount}|${txnid}|${merchantKey}`);if(calculatedHash!==postedHash)return textResponse("invalid hash",400);const admin=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);const nextStatus=status.toLowerCase()==="success"?"confirmed":"cancelled";const {data:appointment,error}=await admin.from("appointments").update({status:nextStatus,payu_mihpayid:mihpayid||null,updated_at:new Date().toISOString()}).eq("payu_txn_id",txnid).select("id").maybeSingle();if(error)return textResponse("appointment update failed",500);if(nextStatus==="confirmed"&&appointment?.id){await awardBundleCredits(admin,txnid);await notifyBooking(appointment.id)}const redirectUrl=buildRedirect(req,nextStatus==="confirmed"?"/payment/success":"/payment/failure");return Response.redirect(redirectUrl,303)}catch(error){console.error("payu-webhook error",error);return textResponse("unexpected PayU webhook error",500)}});
